
/* bf2nasm - brainfuck to nasm compiler */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 */


#include <stdio.h>

int main(void)
{
	int ch;
	int loop = 0;
	int loops[0x10000] = {0};
	char lp = 0;
	char lastop = ' ';		// ` these two is used to optimize the code.
	int  op_cnt = 1;		// / they collect same operations.

	printf(
			"; generated by bf2nasm, "
			"by eXerigumo Clanjor (哆啦比猫/兰威举).\n"
		  );
#ifdef __CYGWIN32__
	printf(
			"%%define main _main\n"
		  );
#endif
	printf(
			"[global main]\n"
			"\n"
			"[section .bss]\n"
			"mem:\tresb 300000\n"
			"\n"
			"[section .text]\n\n"
			"main:\n"
			"\tmov\t\tedi, mem\n\n"		 // the mem pointer
		);

	while ((ch = getchar()) != EOF) {
		if (ch == lastop) op_cnt++;		// collect the same operations
		else {							// when operation changed...
			switch (lastop) {
				case '+':
					if (op_cnt == 1)
						printf("\tinc\t\tbyte [edi]\n");
					else
						printf("\tadd\t\tbyte [edi], %d\n", op_cnt);
					break;

				case '-':
					if (op_cnt == 1)
						printf("\tdec\t\tbyte [edi]\n");
					else
						printf("\tsub\t\tbyte [edi], %d\n", op_cnt);
					break;

				case '>':
					if (op_cnt == 1)
						printf("\tinc\t\tedi\n");
					else
						printf("\tadd\t\tedi, %d\n", op_cnt);
					break;

				case '<':
					if (op_cnt == 1)
						printf("\tdec\t\tedi\n");
					else
						printf("\tsub\t\tedi, %d\n", op_cnt);
					break;

				case ',':
					while (op_cnt--) printf("\tmov\t\teax,3\n"
											"\tmov\t\tebx,1\n"
											"\tmov\t\tecx,edi\n"
											"\tmov\t\tedx,1\n"
											"\tint\t\t0x80\n"
											);
					break;

				case '.':
					while (op_cnt--) printf("\tmov\t\teax,4\n"
											"\tmov\t\tebx,1\n"
											"\tmov\t\tecx,edi\n"
											"\tmov\t\tedx,8\n"
											"\tint\t\t0x80\n");
					break;

				case '[':
					while (op_cnt--) {
						loops[lp] = loop++;
						printf("label_%d_start:\n", loops[lp]);
						printf("\tcmp\t\tbyte [edi], 0\n");
						printf("\tje\t\tlabel_%d_end\n", loops[lp]);
						lp++;
					}
					break;

				case ']':
					while (op_cnt--) {
						lp--;
						printf("\tjmp\t\tlabel_%d_start\n", loops[lp]);
						printf("label_%d_end:\n", loops[lp]);
					}
					break;

				default:	// ignore comments
					break;
			}

			// start collecting new operation
			lastop = ch;
			op_cnt = 1;
		}
	}
	
	//exit()
	printf("\n\nmov eax,1\nmov ebx,1\nint 0x80\n\n");

	// return 0
	printf("\n\txor\t\teax, eax\n");
	printf("\tret\n");

	return 0;
}

