
/* bf2nasm - brainfuck to nasm compiler */

#include <stdio.h>

int main(void)
{
	int ch;
	int loop = 0;
	int loops[0x10000] = {0};
	char lp = 0;
	char lastop = ' ';		// ` these two is used to optimize the code.
	int  op_cnt = 1;		// / they collect same operations.

	printf(
			"; generated by bf2nasm, "
			"by eXerigumo Clanjor (哆啦比猫/兰威举).\n"
		  );
#ifdef __CYGWIN32__
	printf(
			"%%define putchar _putchar\n"
			"%%define getchar _getchar\n"
			"%%define main _main\n"
		  );
#endif
	printf(
			"[extern putchar]\n"
			"[extern getchar]\n"
			"[global main]\n"
			"\n"
			"[section .bss]\n"
			"mem:\tresb 300000\n"
			"\n"
			"[section .text]\n"
			"main:\n"
			"\tmov\t\tedi, mem\n\n"		 // the mem pointer
		);

	while ((ch = getchar()) != EOF) {
		if (ch == lastop) op_cnt++;		// collect the same operations
		else {							// when operation changed...
			switch (lastop) {
				case '+':
					if (op_cnt == 1)
						printf("\tinc\t\tbyte [edi]\n");
					else
						printf("\tadd\t\tbyte [edi], %d\n", op_cnt);
					break;

				case '-':
					if (op_cnt == 1)
						printf("\tdec\t\tbyte [edi]\n");
					else
						printf("\tsub\t\tbyte [edi], %d\n", op_cnt);
					break;

				case '>':
					if (op_cnt == 1)
						printf("\tinc\t\tedi\n");
					else
						printf("\tadd\t\tedi, %d\n", op_cnt);
					break;

				case '<':
					if (op_cnt == 1)
						printf("\tdec\t\tedi\n");
					else
						printf("\tsub\t\tedi, %d\n", op_cnt);
					break;

				case ',':
					while (op_cnt--) printf("\tcall\tgetchar\n");
					printf("\tmov\t\t[edi], al\n");
					break;

				case '.':
					printf("\tpush\tdword [edi]\n");
					while (op_cnt--) printf("\tcall\tputchar\n");
					printf("\tadd\t\tesp, 4\n");
					break;

				case '[':
					while (op_cnt--) {
						loops[lp] = loop++;
						printf("label_%d_start:\n", loops[lp]);
						printf("\tcmp\t\tbyte [edi], 0\n");
						printf("\tje\t\tlabel_%d_end\n", loops[lp]);
						lp++;
					}
					break;

				case ']':
					while (op_cnt--) {
						lp--;
						printf("\tjmp\t\tlabel_%d_start\n", loops[lp]);
						printf("label_%d_end:\n", loops[lp]);
					}
					break;

				default:	// ignore comments
					break;
			}

			// start collecting new operation
			lastop = ch;
			op_cnt = 1;
		}
	}

	// return 0
	printf("\n\txor\t\teax, eax\n");
	printf("\tret\n");

	return 0;
}

